//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 01:26:14 PM AWST 
//


package com.jellyfish77;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImdbId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gross" type="{}NullOrInteger"/>
 *         &lt;element name="Format">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AspectRatio" type="{}NullOrFloat"/>
 *                   &lt;element name="Runtime" type="{}NullOrInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Production">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Countries">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Budget" type="{}NullOrInteger"/>
 *                   &lt;element name="Year" type="{}NullOrInteger"/>
 *                   &lt;element name="ReleaseDate" type="{}nillableDate" minOccurs="0"/>
 *                   &lt;element name="DvdDate" type="{}nillableDate" minOccurs="0"/>
 *                   &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Genres">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Plot">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PlotKeywords">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PlotKeyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Poster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Awards" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserVotes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NumUsersReviewed" type="{}NullOrInteger"/>
 *         &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImdbLink" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacebookLikes" type="{}NullOrInteger"/>
 *         &lt;element name="NumPosterFaces" type="{}NullOrInteger"/>
 *         &lt;element name="Director">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FacebookLikes" type="{}NullOrInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Writers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Writer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NumReviews" type="{}NullOrInteger"/>
 *         &lt;element name="Cast">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Actors">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Actor" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Biling" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FacebookLikes" type="{}NullOrInteger" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ratings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Rating" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "imdbId",
    "gross",
    "format",
    "production",
    "genres",
    "plot",
    "poster",
    "awards",
    "userVotes",
    "numUsersReviewed",
    "rating",
    "imdbLink",
    "country",
    "facebookLikes",
    "numPosterFaces",
    "director",
    "writers",
    "numReviews",
    "cast",
    "ratings"
})
@XmlRootElement(name = "Movie")
public class Movie {

    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "ImdbId", required = true)
    protected String imdbId;
    @XmlElement(name = "Gross", required = true)
    protected String gross;
    @XmlElement(name = "Format", required = true)
    protected Movie.Format format;
    @XmlElement(name = "Production", required = true)
    protected Movie.Production production;
    @XmlElement(name = "Genres", required = true)
    protected Movie.Genres genres;
    @XmlElement(name = "Plot", required = true)
    protected Movie.Plot plot;
    @XmlElement(name = "Poster", required = true)
    protected String poster;
    @XmlElement(name = "Awards", required = true)
    protected String awards;
    @XmlElement(name = "UserVotes")
    protected int userVotes;
    @XmlElement(name = "NumUsersReviewed", required = true)
    protected String numUsersReviewed;
    @XmlElement(name = "Rating", required = true)
    protected String rating;
    @XmlElement(name = "ImdbLink", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String imdbLink;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "FacebookLikes", required = true)
    protected String facebookLikes;
    @XmlElement(name = "NumPosterFaces", required = true)
    protected String numPosterFaces;
    @XmlElement(name = "Director", required = true)
    protected Movie.Director director;
    @XmlElement(name = "Writers", required = true)
    protected Movie.Writers writers;
    @XmlElement(name = "NumReviews", required = true)
    protected String numReviews;
    @XmlElement(name = "Cast", required = true)
    protected Movie.Cast cast;
    @XmlElement(name = "Ratings", required = true)
    protected Movie.Ratings ratings;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the imdbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImdbId() {
        return imdbId;
    }

    /**
     * Sets the value of the imdbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImdbId(String value) {
        this.imdbId = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGross(String value) {
        this.gross = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Format }
     *     
     */
    public Movie.Format getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Format }
     *     
     */
    public void setFormat(Movie.Format value) {
        this.format = value;
    }

    /**
     * Gets the value of the production property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Production }
     *     
     */
    public Movie.Production getProduction() {
        return production;
    }

    /**
     * Sets the value of the production property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Production }
     *     
     */
    public void setProduction(Movie.Production value) {
        this.production = value;
    }

    /**
     * Gets the value of the genres property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Genres }
     *     
     */
    public Movie.Genres getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Genres }
     *     
     */
    public void setGenres(Movie.Genres value) {
        this.genres = value;
    }

    /**
     * Gets the value of the plot property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Plot }
     *     
     */
    public Movie.Plot getPlot() {
        return plot;
    }

    /**
     * Sets the value of the plot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Plot }
     *     
     */
    public void setPlot(Movie.Plot value) {
        this.plot = value;
    }

    /**
     * Gets the value of the poster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoster() {
        return poster;
    }

    /**
     * Sets the value of the poster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoster(String value) {
        this.poster = value;
    }

    /**
     * Gets the value of the awards property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwards() {
        return awards;
    }

    /**
     * Sets the value of the awards property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwards(String value) {
        this.awards = value;
    }

    /**
     * Gets the value of the userVotes property.
     * 
     */
    public int getUserVotes() {
        return userVotes;
    }

    /**
     * Sets the value of the userVotes property.
     * 
     */
    public void setUserVotes(int value) {
        this.userVotes = value;
    }

    /**
     * Gets the value of the numUsersReviewed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumUsersReviewed() {
        return numUsersReviewed;
    }

    /**
     * Sets the value of the numUsersReviewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumUsersReviewed(String value) {
        this.numUsersReviewed = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRating(String value) {
        this.rating = value;
    }

    /**
     * Gets the value of the imdbLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImdbLink() {
        return imdbLink;
    }

    /**
     * Sets the value of the imdbLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImdbLink(String value) {
        this.imdbLink = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the facebookLikes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacebookLikes() {
        return facebookLikes;
    }

    /**
     * Sets the value of the facebookLikes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacebookLikes(String value) {
        this.facebookLikes = value;
    }

    /**
     * Gets the value of the numPosterFaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumPosterFaces() {
        return numPosterFaces;
    }

    /**
     * Sets the value of the numPosterFaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumPosterFaces(String value) {
        this.numPosterFaces = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Director }
     *     
     */
    public Movie.Director getDirector() {
        return director;
    }

    /**
     * Sets the value of the director property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Director }
     *     
     */
    public void setDirector(Movie.Director value) {
        this.director = value;
    }

    /**
     * Gets the value of the writers property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Writers }
     *     
     */
    public Movie.Writers getWriters() {
        return writers;
    }

    /**
     * Sets the value of the writers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Writers }
     *     
     */
    public void setWriters(Movie.Writers value) {
        this.writers = value;
    }

    /**
     * Gets the value of the numReviews property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumReviews() {
        return numReviews;
    }

    /**
     * Sets the value of the numReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumReviews(String value) {
        this.numReviews = value;
    }

    /**
     * Gets the value of the cast property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Cast }
     *     
     */
    public Movie.Cast getCast() {
        return cast;
    }

    /**
     * Sets the value of the cast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Cast }
     *     
     */
    public void setCast(Movie.Cast value) {
        this.cast = value;
    }

    /**
     * Gets the value of the ratings property.
     * 
     * @return
     *     possible object is
     *     {@link Movie.Ratings }
     *     
     */
    public Movie.Ratings getRatings() {
        return ratings;
    }

    /**
     * Sets the value of the ratings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movie.Ratings }
     *     
     */
    public void setRatings(Movie.Ratings value) {
        this.ratings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Actors">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Actor" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Biling" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="FacebookLikes" type="{}NullOrInteger" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actors"
    })
    public static class Cast {

        @XmlElement(name = "Actors", required = true)
        protected Movie.Cast.Actors actors;

        /**
         * Gets the value of the actors property.
         * 
         * @return
         *     possible object is
         *     {@link Movie.Cast.Actors }
         *     
         */
        public Movie.Cast.Actors getActors() {
            return actors;
        }

        /**
         * Sets the value of the actors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Movie.Cast.Actors }
         *     
         */
        public void setActors(Movie.Cast.Actors value) {
            this.actors = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Actor" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Biling" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FacebookLikes" type="{}NullOrInteger" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "actor"
        })
        public static class Actors {

            @XmlElement(name = "Actor")
            protected List<Movie.Cast.Actors.Actor> actor;

            /**
             * Gets the value of the actor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the actor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getActor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Movie.Cast.Actors.Actor }
             * 
             * 
             */
            public List<Movie.Cast.Actors.Actor> getActor() {
                if (actor == null) {
                    actor = new ArrayList<Movie.Cast.Actors.Actor>();
                }
                return this.actor;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Biling" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FacebookLikes" type="{}NullOrInteger" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "biling",
                "name",
                "facebookLikes"
            })
            public static class Actor {

                @XmlElement(name = "Biling")
                protected Byte biling;
                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "FacebookLikes")
                protected String facebookLikes;

                /**
                 * Gets the value of the biling property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getBiling() {
                    return biling;
                }

                /**
                 * Sets the value of the biling property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setBiling(Byte value) {
                    this.biling = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the facebookLikes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFacebookLikes() {
                    return facebookLikes;
                }

                /**
                 * Sets the value of the facebookLikes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFacebookLikes(String value) {
                    this.facebookLikes = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FacebookLikes" type="{}NullOrInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "facebookLikes"
    })
    public static class Director {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "FacebookLikes", required = true)
        protected String facebookLikes;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the facebookLikes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFacebookLikes() {
            return facebookLikes;
        }

        /**
         * Sets the value of the facebookLikes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFacebookLikes(String value) {
            this.facebookLikes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AspectRatio" type="{}NullOrFloat"/>
     *         &lt;element name="Runtime" type="{}NullOrInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "color",
        "language",
        "aspectRatio",
        "runtime"
    })
    public static class Format {

        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "Color", required = true)
        protected String color;
        @XmlElement(name = "Language", required = true)
        protected String language;
        @XmlElement(name = "AspectRatio", required = true)
        protected String aspectRatio;
        @XmlElement(name = "Runtime", required = true)
        protected String runtime;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the aspectRatio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAspectRatio() {
            return aspectRatio;
        }

        /**
         * Sets the value of the aspectRatio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAspectRatio(String value) {
            this.aspectRatio = value;
        }

        /**
         * Gets the value of the runtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRuntime() {
            return runtime;
        }

        /**
         * Sets the value of the runtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRuntime(String value) {
            this.runtime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "genre"
    })
    public static class Genres {

        @XmlElement(name = "Genre")
        protected List<String> genre;

        /**
         * Gets the value of the genre property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genre property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenre().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGenre() {
            if (genre == null) {
                genre = new ArrayList<String>();
            }
            return this.genre;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PlotKeywords">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PlotKeyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "plotKeywords"
    })
    public static class Plot {

        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "PlotKeywords", required = true)
        protected Movie.Plot.PlotKeywords plotKeywords;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the plotKeywords property.
         * 
         * @return
         *     possible object is
         *     {@link Movie.Plot.PlotKeywords }
         *     
         */
        public Movie.Plot.PlotKeywords getPlotKeywords() {
            return plotKeywords;
        }

        /**
         * Sets the value of the plotKeywords property.
         * 
         * @param value
         *     allowed object is
         *     {@link Movie.Plot.PlotKeywords }
         *     
         */
        public void setPlotKeywords(Movie.Plot.PlotKeywords value) {
            this.plotKeywords = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PlotKeyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "plotKeyword"
        })
        public static class PlotKeywords {

            @XmlElement(name = "PlotKeyword")
            protected List<String> plotKeyword;

            /**
             * Gets the value of the plotKeyword property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the plotKeyword property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPlotKeyword().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getPlotKeyword() {
                if (plotKeyword == null) {
                    plotKeyword = new ArrayList<String>();
                }
                return this.plotKeyword;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Countries">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Budget" type="{}NullOrInteger"/>
     *         &lt;element name="Year" type="{}NullOrInteger"/>
     *         &lt;element name="ReleaseDate" type="{}nillableDate" minOccurs="0"/>
     *         &lt;element name="DvdDate" type="{}nillableDate" minOccurs="0"/>
     *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countries",
        "budget",
        "year",
        "releaseDate",
        "dvdDate",
        "website"
    })
    public static class Production {

        @XmlElement(name = "Countries", required = true)
        protected Movie.Production.Countries countries;
        @XmlElement(name = "Budget", required = true)
        protected String budget;
        @XmlElement(name = "Year", required = true)
        protected String year;
        @XmlElement(name = "ReleaseDate")
        protected String releaseDate;
        @XmlElement(name = "DvdDate")
        protected String dvdDate;
        @XmlElement(name = "Website", required = true)
        protected String website;

        /**
         * Gets the value of the countries property.
         * 
         * @return
         *     possible object is
         *     {@link Movie.Production.Countries }
         *     
         */
        public Movie.Production.Countries getCountries() {
            return countries;
        }

        /**
         * Sets the value of the countries property.
         * 
         * @param value
         *     allowed object is
         *     {@link Movie.Production.Countries }
         *     
         */
        public void setCountries(Movie.Production.Countries value) {
            this.countries = value;
        }

        /**
         * Gets the value of the budget property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBudget() {
            return budget;
        }

        /**
         * Sets the value of the budget property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBudget(String value) {
            this.budget = value;
        }

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYear(String value) {
            this.year = value;
        }

        /**
         * Gets the value of the releaseDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReleaseDate() {
            return releaseDate;
        }

        /**
         * Sets the value of the releaseDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReleaseDate(String value) {
            this.releaseDate = value;
        }

        /**
         * Gets the value of the dvdDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDvdDate() {
            return dvdDate;
        }

        /**
         * Sets the value of the dvdDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDvdDate(String value) {
            this.dvdDate = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsite(String value) {
            this.website = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "country"
        })
        public static class Countries {

            @XmlElement(name = "Country")
            protected List<String> country;

            /**
             * Gets the value of the country property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the country property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCountry().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCountry() {
                if (country == null) {
                    country = new ArrayList<String>();
                }
                return this.country;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Rating" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rating"
    })
    public static class Ratings {

        @XmlElement(name = "Rating")
        protected List<Movie.Ratings.Rating> rating;

        /**
         * Gets the value of the rating property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rating property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRating().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Movie.Ratings.Rating }
         * 
         * 
         */
        public List<Movie.Ratings.Rating> getRating() {
            if (rating == null) {
                rating = new ArrayList<Movie.Ratings.Rating>();
            }
            return this.rating;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source",
            "value"
        })
        public static class Rating {

            @XmlElement(name = "Source", required = true)
            protected String source;
            @XmlElement(name = "Value", required = true)
            protected String value;

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Writer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "writer"
    })
    public static class Writers {

        @XmlElement(name = "Writer")
        protected List<String> writer;

        /**
         * Gets the value of the writer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the writer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWriter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getWriter() {
            if (writer == null) {
                writer = new ArrayList<String>();
            }
            return this.writer;
        }

    }

}
