//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 01:26:14 PM AWST 
//


package com.jellyfish77;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link Movie.Ratings }
     * 
     */
    public Movie.Ratings createMovieRatings() {
        return new Movie.Ratings();
    }

    /**
     * Create an instance of {@link Movie.Cast }
     * 
     */
    public Movie.Cast createMovieCast() {
        return new Movie.Cast();
    }

    /**
     * Create an instance of {@link Movie.Cast.Actors }
     * 
     */
    public Movie.Cast.Actors createMovieCastActors() {
        return new Movie.Cast.Actors();
    }

    /**
     * Create an instance of {@link Movie.Plot }
     * 
     */
    public Movie.Plot createMoviePlot() {
        return new Movie.Plot();
    }

    /**
     * Create an instance of {@link Movie.Production }
     * 
     */
    public Movie.Production createMovieProduction() {
        return new Movie.Production();
    }

    /**
     * Create an instance of {@link Movie.Format }
     * 
     */
    public Movie.Format createMovieFormat() {
        return new Movie.Format();
    }

    /**
     * Create an instance of {@link Movie.Genres }
     * 
     */
    public Movie.Genres createMovieGenres() {
        return new Movie.Genres();
    }

    /**
     * Create an instance of {@link Movie.Director }
     * 
     */
    public Movie.Director createMovieDirector() {
        return new Movie.Director();
    }

    /**
     * Create an instance of {@link Movie.Writers }
     * 
     */
    public Movie.Writers createMovieWriters() {
        return new Movie.Writers();
    }

    /**
     * Create an instance of {@link Movie.Ratings.Rating }
     * 
     */
    public Movie.Ratings.Rating createMovieRatingsRating() {
        return new Movie.Ratings.Rating();
    }

    /**
     * Create an instance of {@link Movie.Cast.Actors.Actor }
     * 
     */
    public Movie.Cast.Actors.Actor createMovieCastActorsActor() {
        return new Movie.Cast.Actors.Actor();
    }

    /**
     * Create an instance of {@link Movie.Plot.PlotKeywords }
     * 
     */
    public Movie.Plot.PlotKeywords createMoviePlotPlotKeywords() {
        return new Movie.Plot.PlotKeywords();
    }

    /**
     * Create an instance of {@link Movie.Production.Countries }
     * 
     */
    public Movie.Production.Countries createMovieProductionCountries() {
        return new Movie.Production.Countries();
    }

}
